### ISSUE TITLE
Error creation of database on docker sql server container

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet-architecture/eShopOnWeb#285]
I have been getting issue with setting up docker container, this project does not seem to have guidance toward setting up docker container and docker file are not even updated. I have tried to setup with the following docker files but it does not create or seed Identity database:- 

WebMVC docker file:-

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY ["src/Web/WebUI/WebUI.csproj", "src/Web/WebUI/"]
COPY ["src/Core/Application/Application.csproj", "src/Core/Application/"]
COPY ["src/Infrastructure/Persistence/Persistence.csproj", "src/Infrastructure/Persistence/"]
RUN dotnet restore "src/Web/WebUI/WebUI.csproj"
COPY . .
WORKDIR "/src/src/Web/WebUI"
RUN dotnet build "WebUI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebUI.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebUI.dll"]
```
docker-compose.yml file 

```
version: '3.4'

services:

  sql.data:
   image: mcr.microsoft.com/mssql/server:2017-latest

  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/Web/WebUI/Dockerfile
    depends_on:
      - sql.data
```
docker-compose-override.yml file:-

```
version: '3.4'
services:
  sql.data:
   environment:
    - SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y

   ports:
    - "5433:1433"

  webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=eWebShopDatabase;User=sa;Password=Pass@word
     
    ports:
      - "5107:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
```
appsettings configuration file:-
```
{
  "ConnectionString": "Server=sql.data;Database=eWebShopDatabase;User=sa;Password=Pass@word;"
}
```
docker-compose build succeeded and i can see the image.
docker-compose up would not run but given me following errors.
1. when you run docker-compose up after building it does not seem to fired-up sql server database container therefore it says " A network-related or instance-specific error occured while establishing a connection to SQL Server..." but when you check docker ps command but it shows : mssql server container is running state.
2. Now you open another windows command prompt and type: docker-compose up again 
and it runs and catalogcontextseed data seeded but it does not create appidentitydbcontext table from the migration file therefore it fails to seed the data. 

I tried pretty much as far as i know but could not get it at all. Therefore i have posted this issue here and i would request you to guide through the docker file setup.

This project runs fine and data seed as well if we don't run it on docker orchestrator support. 
I am pretty confused, since program build succeeded through compose file. I don't know whether my docker compose file settings are correct or something missing. 

Your docker compose file in the project seems missing complete setup.
